// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace TranslateIntoChinese
{
    internal sealed partial class Vsix
    {
        public const string Id = "vsix_MoqDictionary.922bb0c3-ecc3-4e62-b60e-6a51f090bc7f";
        public const string Name = "TranslateIntoChinese";
        public const string Description = @"TranslateIntoChinese 是 Visual Studio 划词翻译插件：离线词库、选区/句子翻译、文档注释翻译，并支持 LM Studio / OpenAI-Compatible / Anthropic / Ollama 大模型。";
        public const string Language = "zh-Hans";
        public const string Version = "1.5.1";
        public const string Author = "Entity-now";
        public const string Tags = "";
    }
}
