// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace TranlateIntoChinese
{
    internal sealed partial class Vsix
    {
        public const string Id = "TranlateIntoChinese.d5663168-0b3d-483d-9665-f8bdc90e94aa";
        public const string Name = "TranlateIntoChinese";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "zh-Hans";
        public const string Version = "1.0";
        public const string Author = "DDD D";
        public const string Tags = "";
    }
}
