// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace TranlateIntoChinese
{
    internal sealed partial class Vsix
    {
        public const string Id = "vsix_EnTranslate.922bb0c3-ecc3-4e62-b60e-6a51f090bc7f";
        public const string Name = "TranlateIntoChinese";
        public const string Description = @"EnTranslate是一款功能强大的离线划词翻译插件，拥有超过340万条离线词库，能够准确翻译各种生僻单词。作为Visual Studio的VSIX插件，它为您提供了出色的英语单词翻译功能，而且具备灵活的单词拆分能力，支持驼峰命名和下划线命名等多种形式的单词拆分。无论您是在编写代码还是阅读文档，EnTranslate都是您的最佳翻译助手。";
        public const string Language = "zh-Hans";
        public const string Version = "1.3.1";
        public const string Author = "DDD D";
        public const string Tags = "";
    }
}
