// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace TranlateIntoChinese
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string TranlateIntoChineseString = "c47bdd20-91d7-4458-adb0-f94598cf3de3";
        public static Guid TranlateIntoChinese = new Guid(TranlateIntoChineseString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int TranslateIntoChineseGroup = 0x0001;
        public const int ShowSettingsCommand = 0x0100;
        public const int MenuGroup = 0x0111;
    }
}